* Proposition de projet

Proposition de projet de développement dans le cadre du cours 420-G55.

La proposition doit être approuvée par l'enseignant. Par contre, les détails (sauf les membres de l'équipe) sont sujets à changement selon les circonstances au cours du développement avec l'accord de l'enseignant.

** Équipe

- Nom des coéquipiers (3 ou 4 personnes) :
  1 : Ali Benkarrouch
  2 : Jamil Fayad
  3 : Ismail El Asraoui
  4 : Aziz Rayene Delaa
  
- Horaire de rencontre hebdomadaire (1h) : Dimanche 13h

** Projet

- Thématique (quel est le domaine d'application de votre travail) : Application de réservations de chambre d'hotel
  
- Problème à résoudre (du point de vue de l'utilisateur, quel sera la plus-value de votre app) : Permettre aux clients réserver une chambre dans un hôtel et aux employés de facilement gérer les chambres et réservations.
  
- Analyse comparative (nommez au moins deux applications (Android ou non) déjà existantes qui font plus ou moins la même chose) : AirBnB, Expedia

  
** Fonctionnalités minimales :

*** Sauvegarde locale d'informations utilisateurs
Quelles données comptez-vous stoquer localement sur l'appareil? : Les préférences (Mode lumière ou sombre, langue)

*** Échange de données avec un service extérieur
Quelles données comptez-vous échanger avec un service extérieur? : Les chambres et réservations


L'API existe-t-il déjà? : Non, bientôt (Service d'échange de données).
Si oui, est-il accessible librement? gratuitement? devez-vous l'héberger vous-même? : Accessible librement 
Si non, sera-t-il développé et par qui? ou simulé? :  L'Api sera développé par l'équipe actuel dans le cours d'échange de données
Si déjà connu, de quel type d'API s'agit-il?
  - REST

*** Interaction avec d'autres applications du système Android
Quelle(s) fonctionnalité(s] fer(a|ont) appel à une autre application du système?
(ex.: prise de photo/vidéo, envoie de courriel, ajout de rendez-vous au calendrier, etc.) : Caméra du téléphone (pour obtenir la carte d'identité)


*** Licence choisie :
- ☐ Propriétaire
- Libre
  ☐ GPLv2 : (peut être utilisée au cœur d'un système non-libre)
  ☐ GPLv3 : (ne peut pas être utilisée au cœur d'un système non-libre)
  ☐ MIT : peut être utilisée dans n'importe quelle circonstance
  ☐ Autre, laquelle? :
  X à déterminer
