* Présentation de groupe
** Date : entre le 16 et le 20 décembre (à confirmer)

** Évaluation
Tous les membres de l'équipe doivent être présents et participer à la présentation (c'est-à-dire, que chacun doit parler à tour de rôle)

*** Les points essentiels de la présentation sont :

- Démonstration dans un émulateur des fonctionnalités de l'application
- Démonstration de l'échange de données avec un service distant (réel ou factice)
- Démonstration de l'interaction avec une ou des applications du système Android

****  Seront évalués :

- La présence des éléments requis
- La qualité de l'ergonomie de l'interface utilisateur
- La robustesse de l'application, par exemple lors de  :

  - la perte de connexion réseau
  - le passage à l'arrière-plan
  - la rotation de l'écran

- La Qualité de la présentation, soit :

  - La clarté du propos
  - La participation individuelle
  - La pertinence des démonstrations
    
*** Questions individuelles
Chaque membre de l'équipe devra répondre à une ou plusieurs questions techniques sur le projet. Ces questions peuvent porter, entre autres, sur :

- L'architecture générale
- L'étendue des tests unitaires
- Le fonctionnement des sources de données
- Le format d'échange des données
- etc.

C'est la pertinence et la justesse de la réponse qui sont évaluées, pas l'objet de la question. C'est-à-dire que si, par exemple, l'architecture du projet comporte des problèmes, votre réponse doit les mentionner honnêtement et non les minimiser ou les passer sous le tapis.

**** Seront évaluées :

- La connaissance technique du projet
- La capacité à expliquer les détails du projet
- La clarté du propos
- La qualité de la langue
