* Sprint 3

** À faire dans ce sprint

Ce sprint a pour objectif l'établissement de la connexion aux services externes. Ceci implique :

- La gestion des fils d'exécutions par les présentateurs
- L'injection de dépendance via des interfaces pour :
  - Vues
  - Modèle
  - Présentateur
  - Source de données
- L'implémentation d'au moins une source de données «bidon» qui simule l'accès aux données réelles par des données codées en dur.
- L'implémentation d'une source de données «locale» pour l'accès aux données stoquées sur l'appareil (par exemple dans une BD ou un fichier).
- La validations par tests unitaires des :
  - Modèle
  - Présentateur

Facultativement, automatisez l'exécution de vos tests unitaires par un «pipeline» dans gitlab.

** Présentation

Vous devrez présenter, en équipe complète, votre application «fonctionnelle». Les écrans doivent être fonctionnels, mais les données seront évidemment simulés.

Vous n'avez pas à présenter le code, mais il devra être accessible sur Gitlab

- Durée : max 10 min.
- Date : 18/19 novembre
